name: BhawaniSilver
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'


dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  fluttertoast: ^8.2.1
  flutter_spinkit: ^5.1.0
  google_fonts: ^4.0.4
  cloud_firestore: 4.6.0
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.0
  get_storage: ^2.1.1
  carousel_slider: ^4.2.1
  lottie: ^2.5.0
  flutter_stripe: ^9.3.0

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - animations/


