// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmj4Z_dG_usXXNwmfW82rWrKXp7yE8flk',
    appId: '1:584596413504:web:c69c0f59e47a5c482dd3a5',
    messagingSenderId: '584596413504',
    projectId: 'bhawanisilver-f55b2',
    authDomain: 'bhawanisilver-f55b2.firebaseapp.com',
    storageBucket: 'bhawanisilver-f55b2.appspot.com',
    measurementId: 'G-M731RPDPPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwa7ZYmeanahZpvnxlyZydkq12YHF_pSs',
    appId: '1:584596413504:android:10489287a63faafe2dd3a5',
    messagingSenderId: '584596413504',
    projectId: 'bhawanisilver-f55b2',
    storageBucket: 'bhawanisilver-f55b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPJxLyySZ4B-pxb64lBSYKca1mMY-Lm58',
    appId: '1:584596413504:ios:9ef521416ceb570c2dd3a5',
    messagingSenderId: '584596413504',
    projectId: 'bhawanisilver-f55b2',
    storageBucket: 'bhawanisilver-f55b2.appspot.com',
    iosClientId: '584596413504-jasj3ta47qukf1qcgj7tohohc78ubp8t.apps.googleusercontent.com',
    iosBundleId: 'com.bhawani.bhawaniSilver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPJxLyySZ4B-pxb64lBSYKca1mMY-Lm58',
    appId: '1:584596413504:ios:9ef521416ceb570c2dd3a5',
    messagingSenderId: '584596413504',
    projectId: 'bhawanisilver-f55b2',
    storageBucket: 'bhawanisilver-f55b2.appspot.com',
    iosClientId: '584596413504-jasj3ta47qukf1qcgj7tohohc78ubp8t.apps.googleusercontent.com',
    iosBundleId: 'com.bhawani.bhawaniSilver',
  );
}
