// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACoI5RfyNvjFcO-JhqFWywxYj2xOmil5Y',
    appId: '1:741542999889:web:fe2f4b91d004a994d30570',
    messagingSenderId: '741542999889',
    projectId: 'bhawanisilver-40e78',
    authDomain: 'bhawanisilver-40e78.firebaseapp.com',
    storageBucket: 'bhawanisilver-40e78.appspot.com',
    measurementId: 'G-033GG82PW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyok6uxh-pwMdKJ7So8pfw4GpIP6e1HCg',
    appId: '1:741542999889:android:6d30ad1c19ffccdad30570',
    messagingSenderId: '741542999889',
    projectId: 'bhawanisilver-40e78',
    storageBucket: 'bhawanisilver-40e78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkCZYMyIEuCF4TJMxqkcXWXWIgL-Xoh80',
    appId: '1:741542999889:ios:a8964f12c5121d0fd30570',
    messagingSenderId: '741542999889',
    projectId: 'bhawanisilver-40e78',
    storageBucket: 'bhawanisilver-40e78.appspot.com',
    iosClientId: '741542999889-er31sralel7q7jner56kqkphl1qvdahb.apps.googleusercontent.com',
    iosBundleId: 'com.bhawani.bhawaniSilver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkCZYMyIEuCF4TJMxqkcXWXWIgL-Xoh80',
    appId: '1:741542999889:ios:a8964f12c5121d0fd30570',
    messagingSenderId: '741542999889',
    projectId: 'bhawanisilver-40e78',
    storageBucket: 'bhawanisilver-40e78.appspot.com',
    iosClientId: '741542999889-er31sralel7q7jner56kqkphl1qvdahb.apps.googleusercontent.com',
    iosBundleId: 'com.bhawani.bhawaniSilver',
  );
}
